apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: petclinic-database
  namespace: my-apps
spec:
  classRef:
    name: postgresql-unmanaged
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      autoscaling.knative.dev/maxScale: "10"
      autoscaling.knative.dev/scaleDownDelay: 10m
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: scanning_source_policy
    value: scan-policy-relaxed
  - name: scanning_image_policy
    value: scan-policy-relaxed
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: settings-xml
  build:
    env:
    - name: BP_GRADLE_BUILD_FILE
      value: skip
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  source:
    git:
      url: https://git.tap.h2o-4-16714.h2o.vmware.com/tanzu/spring-petclinic
      ref:
        branch: main
  serviceClaims:
    - name: postgres-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: petclinic-database