#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: #@ "{}".format(data.values.imported.git.host)
type: kubernetes.io/basic-auth
data:
  username: #@ base64.encode(data.values.imported.git.username)
  password: #@ base64.encode(data.values.imported.git.password)
  caFile: #@ base64.encode(data.values.imported.git.caFile)