apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-testing-scanning-add-source-scanner
  namespace: tap-install
stringData:
  patch.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"source-test-scan-to-url"}, "kind": "ClusterSupplyChain"})
    ---
    spec:
      resources:
        #@overlay/match by=overlay.index(2)
        #@overlay/insert before=True
           - name: source-scanner
             params:
             - default: scan-policy
               name: scanning_source_policy
             - default: blob-source-scan-template
               name: scanning_source_template
             sources:
             - name: source
               resource: source-tester
             templateRef:
               kind: ClusterSourceTemplate
               name: source-scanner-template
           #@overlay/match by="name"
           - name: image-provider
             sources:
             #@overlay/match by="name"
             - name: source
               resource: source-scanner
---
apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-testing-scanning-add-source-scanner-override
  namespace: tap-install 
stringData:
  patch.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ def matchOOTB(index, left, right):
    #@   if left["apiVersion"] != "packaging.carvel.dev/v1alpha1" or left["kind"] != "PackageInstall":
    #@     return False
    #@   end      
    #@   return left["metadata"]["name"].startswith("ootb-supply-chain-testing-scanning")
    #@ end
    #@overlay/match by=matchOOTB, expects="0+"
    ---
    metadata:
      annotations:
        #@overlay/match missing_ok=True
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ootb-supply-chain-testing-scanning-add-source-scanner